---
# maintains versions and can overwrite all.yml
ethereum:
  nethermind:
    version: 1.35.8-c066aee2
  geth:
    version: 1.16.8-abeb78c6
  lighthouse:
    version: v8.0.1
  prysm:
    version: v7.1.1
  mevboost:
    version: 1.10.1

ssv:
  node:
    version: v2.3.7
    go:
      version: 1.24.2
  dkg:
    version: v3.0.3
    go:
      version: 1.21.0

obol:
  charon:
    version: v1.7.1
    go:
      version: 1.25.4
  ejector:
    version: 1.9.0
    node:
      version: v16.20.2
  dv_exit:
    version: v0.4.0
    go:
      version: 1.25.0
  lodestar:
    version: v1.37.0
