---
# maintains versions and can overwrite all.yml
ethereum:
  nethermind:
    version: 1.35.2-faa9b9e6
  geth:
    version: 1.16.7-b9f3a3d9
  lighthouse:
    version: v8.0.0
  prysm:
    version: v6.1.4
  mevboost:
    version: 1.9

ssv:
  node:
    version: v2.3.6
    go:
      version: 1.24.2
  dkg:
    version: v3.0.3
    go:
      version: 1.21.0

obol:
  charon:
    version: v1.5.1
    go:
      version: 1.24.2
  ejector:
    version: 1.7.0
    node:
      version: v16.20.2
  dv_exit:
    version: v0.3.0
    go:
      version: 1.23.5
  lodestar:
    version: v1.31.0
