---
# maintains versions and can overwrite all.yml
ethereum:
  nethermind:
    version: 1.35.2-faa9b9e6
    ports:
      engine: 8515
      network_discovery: 30330
      p2p: 30330
      json_rpc: 8525
      metrics: 6006
  lighthouse:
    version: v8.0.0
    ports:
      p2p: 8001
      quic: 8002
      http: 5012
      metrics: 8009
  mevboost:
    version: 1.9

obol:
  charon:
    version: v1.7.1
    go:
      version: 1.25.4
  lodestar:
    version: v1.36.0
    suggested_fee_recipient: "0x9b108015fe433F173696Af3Aa0CF7CDb3E104258"
