---
- name: Setup Prometheus
  hosts: all
  become: true
  gather_facts: true
  vars:
    node_service_identifier: "{{ group_names[0] }}"
    service_group: "{{ group_names[0] }}-{{ cluster }}"
    system_architecture: "{{ ansible_system | lower }}-{{ architecture_map[ansible_architecture] | default(ansible_architecture) }}"
  vars_files:
    - group_vars/all.yml
    - group_vars/default.yml
    - group_vars/vault.yml
    - group_vars/{{ env }}.yml

  tasks:
    - name: Set service_identifier
      ansible.builtin.set_fact:
        service_identifier: "{{ node_service_identifier }}-{{ prometheus.service_identifier_suffix }}-{{ cluster }}"

    - name: Include common handlers
      ansible.builtin.include_role:
        name: common
    - name: Include prometheus role
      ansible.builtin.include_role:
        name: prometheus
