---
- name: Include user creation task for prometheus
  ansible.builtin.include_tasks: tasks/create_user_and_directories.yml
  vars:
    home: "{{ prometheus_home_dir }}"
    directories: "{{ prometheus_directories }}"
    log_file_path: "{{ prometheus_log_file_path }}"

- name: Include Download, Unarchive and Copy Binary task
  ansible.builtin.include_tasks: tasks/extract_binary.yml
  vars:
    extracted_binary_dir: "{{ prometheus_default_binary_name }}-{{ prometheus.version }}.{{ system_architecture }}"
    source_url: "{{ prometheus.source_url }}/v{{ prometheus.version }}"
    suffix_url: "{{ prometheus_default_binary_name }}-{{ prometheus.version }}.{{ system_architecture }}.{{ prometheus.file_extension }}"
    binary_dest_path: "{{ prometheus_bin_dir }}/{{ service_identifier }}"
    extracted_binary_path: "{{ extracted_binary_dir }}/{{ prometheus_default_binary_name }}"

- name: Copy prometheus config
  ansible.builtin.template:
    src: "{{ env }}/{{ cluster }}/config.yml.j2"
    dest: "{{ prometheus_config_file_path }}"
    owner: "{{ service_identifier }}"
    group: "{{ service_identifier }}"
    mode: "0600"
  notify:
    - Restart service

- name: Copy prometheus service file
  ansible.builtin.template:
    src: "{{ env }}/{{ cluster }}/systemd.service.j2"
    dest: /etc/systemd/system/{{ service_identifier }}.service
    owner: root
    group: root
    mode: "0644"
  notify:
    - Reload service
    - Restart service
